config/routes.rb
Rhaiku::Application.routes.draw do
  resources :words

  get "pages/home"
  get "pages/contact"
  get "pages/about"

  root :to => 'pages#home'

end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :syllables, :word

  validates :word, :uniqueness => true,
                   :format => /\A[a-zA-z]+\z/,
                   :presence => true

  validates :syllables, :presence => true,
                        :numericality => {
                          :greater_than => 0,
                          :less_than => 8
                        }

  def to_verbose_s
    "#{word} #{syllables}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = 'Home'
  end

  def contact
    @title = 'Contact'
  end

  def about
    @title = 'About'
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @words = Word.order('syllables')
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.new(params[:word])
    if @word.save
      flash[:success] = "Success!"
      redirect_to(words_path)
    else
      @title = 'Create Word'
      render :new
    end
  end

  def edit
    @word = Word.find_by_id(params[:id])
    @title = 'Edit Word'
  end

  def update
    @word = Word.find_by_id(params[:id])
    if @word.update_attributes(params[:word])
      flash[:success] = "Successfully updated #{@word}"
      redirect_to @word
    else
      render :edit
    end
  end

  def show
    @word = Word.find_by_id(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/haiku_generator.rb
module HaikuGenerator
  class Haiku
    attr_reader :first_line, :second_line, :third_line
    def initialize(first_line, second_line, third_line)
      @first_line = first_line
      @second_line = second_line
      @third_line = third_line
    end

    def to_s
      [first_line, second_line, third_line].join("\n")
    end
  end

  class HaikuGenerator
    attr_reader :phrase_generator

    def initialize
      @phrase_generator = PhraseGenerator.new
    end

    def generate
      Haiku.new(phrase_generator.generate(5),
                phrase_generator.generate(7),
                phrase_generator.generate(5))
    end

  end

  class PhraseGenerator 
    attr_reader :word_chooser

    def initialize
      @word_chooser = WordChooser.new
    end

    def generate(syllables)
      phrase = []
      until syllables.zero?
        syllable = random_syllable(syllables)
        # TODO: getting around a bug
        next if syllable > 3
        phrase << word_chooser.choose(syllable)
        syllables -= syllable
      end
      return phrase.join(' ')
    end

    def random_syllable(upper_bound)
      # TODO: this doesn't always work, so I hack it
      return (rand(upper_bound + 1) % upper_bound) + 1
    end

  end

  class WordChooser
    def choose(syllable_count)
      possible_words = Word.
      return possible_words.sample
    end
  end

  # Not going to use this
  class WordBank
    class << self; attr_reader :word_bank end

    def self.word_bank
      require 'yaml'
      @word_bank ||=  YAML.load_file('word_base.yaml')
    end

    def self.get_words_with(syllable_count)
      return word_bank[syllable_count]
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  include HaikuGenerator

  def haiku_generator
    @haiku_generator ||= HaikuGenerator.new
  end

  def title
    base_title = "Rhaiku"
    if @title
      return "#{base_title} | #{@title}"
    else
      return "#{base_title}"
    end
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Rhaiku 俳句</h1>
<%= haiku_generator.methods  %>
<%= link_to('Find your Zen') %>

app/views/shared/_error_messages.html.erb
<% if @word.errors.any? %>
	<p>There were problems with the following fields:</p>
	<ul>
	<% @word.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
	</ul>
<% end %>

app/views/words/_words.html.erb
<%= form_for(@word) do |f| %>
  <%= render 'shared/error_messages' %>
  <%= f.label :word %>
  <%= f.text_field :word %>

  <%= f.label :syllables %>
  <%= f.number_field :syllables %>

  <%= f.submit 'Save' %>
<% end %>

app/views/words/edit.html.erb
<%= render :partial => 'words', @object => @word %>

app/views/words/index.html.erb
<h1>Words</h1>
<% @words.each do |word| %>
  <li><%= word.to_verbose_s %><%= link_to('Edit', edit_word_path(word)) %></li>
<% end %>

<%= link_to('New Word', new_word_path) %>

app/views/words/new.html.erb
<%= render :partial => 'words', :object => @word %>

app/views/words/show.html.erb
<b><%= @word.word %></b><br />
<b><%= @word.syllables %></b>